## import check

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import xgboost as xgb
from bs4 import BeautifulSoup
import requests
import whois

print("All libraries imported successfully!")
print("pandas:", pd.__version__)
print("scikit-learn imported OK")
print("xgboost:", xgb.__version__)

All libraries imported successfully!
pandas: 3.0.0
scikit-learn imported OK
xgboost: 3.3.0

## Load the PhiUSIIL dataset (primary dataset)

In [4]:
from ucimlrepo import fetch_ucirepo

# fetch dataset (id=967 is PhiUSIIL)
phiusiil = fetch_ucirepo(id=967)

# data as pandas dataframes
X = phiusiil.data.features
y = phiusiil.data.targets

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (235795, 54)
Target shape: (235795, 1)

## Save a local copy

In [5]:
df = pd.concat([X, y], axis=1)
df.to_csv('../data/phiusiil_raw.csv', index=False)
print("Saved to data/phiusiil_raw.csv")
print("Shape:", df.shape)

Saved to data/phiusiil_raw.csv
Shape: (235795, 55)

## looking at the data

In [6]:
df.head()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,0,0,1,34,20,28,119,0,124,1
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,1,50,9,8,39,0,217,1
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,0,1,244,15,34,72,1,85,1

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 55 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URL                         235795 non-null  str
 1   URLLength                   235795 non-null  int64
 2   Domain                      235795 non-null  str
 3   DomainLength                235795 non-null  int64
 4   IsDomainIP                  235795 non-null  int64
 5   TLD                         235795 non-null  str
 6   URLSimilarityIndex          235795 non-null  float64
 7   CharContinuationRate        235795 non-null  float64
 8   TLDLegitimateProb           235795 non-null  float64
 9   URLCharProb                 235795 non-null  float64
 10  TLDLength                   235795 non-null  int64
 11  NoOfSubDomain               235795 non-null  int64
 12  HasObfuscation              235795 non-null  int64
 13  NoOfObfuscatedChar          235795 non-null  int64
 14  ObfuscationRatio            235795 non-null  float64
 15  NoOfLettersInURL            235795 non-null  int64
 16  LetterRatioInURL            235795 non-null  float64
 17  NoOfDegitsInURL             235795 non-null  int64
 18  DegitRatioInURL             235795 non-null  float64
 19  NoOfEqualsInURL             235795 non-null  int64
 20  NoOfQMarkInURL              235795 non-null  int64
 21  NoOfAmpersandInURL          235795 non-null  int64
 22  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 23  SpacialCharRatioInURL       235795 non-null  float64
 24  IsHTTPS                     235795 non-null  int64
 25  LineOfCode                  235795 non-null  int64
 26  LargestLineLength           235795 non-null  int64
 27  HasTitle                    235795 non-null  int64
 28  Title                       235795 non-null  str
 29  DomainTitleMatchScore       235795 non-null  float64
 30  URLTitleMatchScore          235795 non-null  float64
 31  HasFavicon                  235795 non-null  int64
 32  Robots                      235795 non-null  int64
 33  IsResponsive                235795 non-null  int64
 34  NoOfURLRedirect             235795 non-null  int64
 35  NoOfSelfRedirect            235795 non-null  int64
 36  HasDescription              235795 non-null  int64
 37  NoOfPopup                   235795 non-null  int64
 38  NoOfiFrame                  235795 non-null  int64
 39  HasExternalFormSubmit       235795 non-null  int64
 40  HasSocialNet                235795 non-null  int64
 41  HasSubmitButton             235795 non-null  int64
 42  HasHiddenFields             235795 non-null  int64
 43  HasPasswordField            235795 non-null  int64
 44  Bank                        235795 non-null  int64
 45  Pay                         235795 non-null  int64
 46  Crypto                      235795 non-null  int64
 47  HasCopyrightInfo            235795 non-null  int64
 48  NoOfImage                   235795 non-null  int64
 49  NoOfCSS                     235795 non-null  int64
 50  NoOfJS                      235795 non-null  int64
 51  NoOfSelfRef                 235795 non-null  int64
 52  NoOfEmptyRef                235795 non-null  int64
 53  NoOfExternalRef             235795 non-null  int64
 54  label                       235795 non-null  int64
dtypes: float64(10), int64(41), str(4)
memory usage: 115.9 MB

In [8]:
df.describe()

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
count,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,...,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000
mean,34.573095,21.470396,0.002706,78.430778,0.845508,0.260423,0.055747,2.764456,1.164758,0.002057,...,0.237007,0.023474,0.486775,26.075689,6.333111,10.522305,65.071113,2.377629,49.262516,0.571895
std,41.314153,9.150793,0.051946,28.976055,0.216632,0.251628,0.010587,0.599739,0.600969,0.045306,...,0.425247,0.151403,0.499826,79.411815,74.866296,22.312192,176.687539,17.641097,161.027430,0.494805
min,13.000000,4.000000,0.000000,0.155574,0.000000,0.000000,0.001083,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,16.000000,0.000000,57.024793,0.680000,0.005977,0.050747,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,27.000000,20.000000,0.000000,100.000000,1.000000,0.079963,0.057970,3.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,8.000000,2.000000,6.000000,12.000000,0.000000,10.000000,1.000000
75%,34.000000,24.000000,0.000000,100.000000,1.000000,0.522907,0.062875,3.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,29.000000,8.000000,15.000000,88.000000,1.000000,57.000000,1.000000
max,6097.000000,110.000000,1.000000,100.000000,1.000000,0.522907,0.090824,13.000000,10.000000,1.000000,...,1.000000,1.000000,1.000000,8956.000000,35820.000000,6957.000000,27397.000000,4887.000000,27516.000000,1.000000

In [9]:
# check class balance (1 = legitimate, 0 = phishing)
df['label'].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

In [10]:
pip install kaggle

Requirement already satisfied: kaggle in /opt/miniconda3/lib/python3.13/site-packages (2.2.4)
Requirement already satisfied: bleach in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (0.1.35)
Requirement already satisfied: packaging in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (24.2)
Requirement already satisfied: protobuf in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (6.33.5)
Requirement already satisfied: python-dateutil in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/miniconda3/lib/python3.13/site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in /opt/miniconda3/lib/python3.13/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /opt/miniconda3/lib/python3.13/site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in /opt/miniconda3/lib/python3.13/site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /opt/miniconda3/lib/python3.13/site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /opt/miniconda3/lib/python3.13/site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/miniconda3/lib/python3.13/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.13/site-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /opt/miniconda3/lib/python3.13/site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/miniconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/miniconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/miniconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /opt/miniconda3/lib/python3.13/site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.3.7)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import subprocess
subprocess.run(['kaggle', 'datasets', 'download', '-d', 'ndarvind/phiusiil-phishing-url-dataset', '-p', '../data/', '--unzip'])

Dataset URL: https://www.kaggle.com/datasets/ndarvind/phiusiil-phishing-url-dataset
License(s): CC-BY-NC-SA-4.0
Downloading phiusiil-phishing-url-dataset.zip to ../data

 95%|█████████▌| 14.0M/14.7M [00:04<00:00, 4.75MB/s]

100%|██████████| 14.7M/14.7M [00:04<00:00, 3.51MB/s]

CompletedProcess(args=['kaggle', 'datasets', 'download', '-d', 'ndarvind/phiusiil-phishing-url-dataset', '-p', '../data/', '--unzip'], returncode=0)

In [12]:
import os
os.listdir('../data')

['phiusiil_raw.csv', 'PhiUSIIL_Phishing_URL_Dataset.csv']

In [13]:
kaggle_df = pd.read_csv('../data/PhiUSIIL_Phishing_URL_Dataset.csv')
print("Kaggle version shape:", kaggle_df.shape)
kaggle_df.head()

Kaggle version shape: (235795, 55)

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,0,0,1,34,20,28,119,0,124,1
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0,0,1,50,9,8,39,0,217,1
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0,0,1,10,2,7,42,2,5,1
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1,1,1,3,27,15,22,1,31,1
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1,0,1,244,15,34,72,1,85,1